name: yakushima_guide
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  image_picker: ^1.0.4
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  google_maps_flutter: ^2.5.0
  firebase_core: ^2.25.4
  firebase_auth: ^4.17.4
  firebase_storage: ^11.6.4
  cloud_firestore: ^4.17.4
  flutter_riverpod: ^2.6.1
  google_fonts: ^6.1.0
  go_router: ^13.2.2
  uuid: ^4.2.2
  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  intl: ^0.19.0
  js: ^0.6.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6
  freezed: ^2.4.5
  json_serializable: ^6.7.1
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
