// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPH4nlEuFQ28CCcjPTIXfbqsi3_qJnYbo',
    appId: '1:34049309500:web:5ec6c0a0935d1d9642bc39',
    messagingSenderId: '34049309500',
    projectId: 'yakushima-guide-2d06f',
    authDomain: 'yakushima-guide-2d06f.firebaseapp.com',
    storageBucket: 'yakushima-guide-2d06f.firebasestorage.app',
    measurementId: 'G-VCJ6NYY4TT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBS2ZqJoSYuze-I64eh3DthIHVLIF64jTk',
    appId: '1:34049309500:android:5eecdba2bfb5d66542bc39',
    messagingSenderId: '34049309500',
    projectId: 'yakushima-guide-2d06f',
    storageBucket: 'yakushima-guide-2d06f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGBRCC3spCjwUYTY8eDL7fC_Pcowmuyzw',
    appId: '1:34049309500:ios:c9ea60396387fc4242bc39',
    messagingSenderId: '34049309500',
    projectId: 'yakushima-guide-2d06f',
    storageBucket: 'yakushima-guide-2d06f.firebasestorage.app',
    iosBundleId: 'com.example.yakushimaGuide',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGBRCC3spCjwUYTY8eDL7fC_Pcowmuyzw',
    appId: '1:34049309500:ios:c9ea60396387fc4242bc39',
    messagingSenderId: '34049309500',
    projectId: 'yakushima-guide-2d06f',
    storageBucket: 'yakushima-guide-2d06f.firebasestorage.app',
    iosBundleId: 'com.example.yakushimaGuide',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDPH4nlEuFQ28CCcjPTIXfbqsi3_qJnYbo',
    appId: '1:34049309500:web:2d8bdecac9616cd942bc39',
    messagingSenderId: '34049309500',
    projectId: 'yakushima-guide-2d06f',
    authDomain: 'yakushima-guide-2d06f.firebaseapp.com',
    storageBucket: 'yakushima-guide-2d06f.firebasestorage.app',
    measurementId: 'G-CLGCD9TV4S',
  );

}